---
## 1. firewalldのポート許可
- name: check_install /Allow prots for firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ nginx_firewalld_port }}"
