---
## 1. Remiリポジトリの登録
- name: install / Import repository
  get_url:
    url: http://rpms.famillecollect.com/enterprise/remi.repo
    dest: /etc/yjm.repos.d/remi.repo
    mode: 0644

## 2. PHP-FPMのインストール
- name: install / Install required packages
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: remi-php56
  with_items: "{{ php_packages }}"
