---
haproxy_frontend_address: "{{ hostvars.app_v1i.ansible_host }}"
haproxy_frontend_port: 80
haproxy_frontend_option:
  - "maxconn 1000"
haproxy_backend_port: 8080
haproxy_backend_app: "{{ cluster_service }}"
haproxy_backend_groups: apps
haproxy_backend_option:
  - "balance source"
  - "http-request set-header Host {{ hostvars.app_v1i.ansible_host }}"
haproxy_firewalld_port:
  - "{{ haproy_stats_port }}"/tcp
  - "{{ haproxy_frontend_port }}/tcp"
